version: "3.9"
services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=ftdh726@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"

  site:
    image: ghcr.io/<user>/<repo>:latest
    env_file: /opt/site/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`fynora.fr`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls.certresolver=le"
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  letsencrypt:
