name: Test SSH (agent)
on: workflow_dispatch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH agent with our key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}   # clé privée OpenSSH multi-lignes

      - name: Trust host key (avoid interactive prompt)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Run remote command
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "echo ✅ OK && whoami && uname -a"
