name: Test SSH
on: workflow_dispatch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ Connexion réussie depuis GitHub Actions vers le VPS"
            uname -a
            ls -la ~
